package com.example.technica_valtracker.api.constants;

/**
 * Handles the retrieval of a champion's name by their ID. A String array is returned because occasionally, the
 * champion's displayed name and the one used for obtaining their Icon are different.
 */
public class Champions {
    public static String[] getChampionById(long id) {
        return switch ((int) id) {
            case 266 -> new String[] {"Aatrox"};
            case 103 -> new String[] {"Ahri"};
            case 84 -> new String[] {"Akali"};
            case 166 -> new String[] {"Akshan"};
            case 12 -> new String[] {"Alistar"};
            case 32 -> new String[] {"Amumu"};
            case 34 -> new String[] {"Anivia"};
            case 1 -> new String[] {"Annie"};
            case 523 -> new String[] {"Aphelios"};
            case 22 -> new String[] {"Ashe"};
            case 136 -> new String[] {"Aurelion Sol", "AurelionSol"};
            case 893 -> new String[] {"Aurora"};
            case 268 -> new String[] {"Azir"};
            case 432 -> new String[] {"Bard"};
            case 200 -> new String[] {"Bel'Veth", "Belveth"};
            case 53 -> new String[] {"Blitzcrank"};
            case 63 -> new String[] {"Brand"};
            case 201 -> new String[] {"Braum"};
            case 233 -> new String[] {"Briar"};
            case 51 -> new String[] {"Caitlyn"};
            case 164 -> new String[] {"Camille"};
            case 69 -> new String[] {"Cassiopeia"};
            case 31 -> new String[] {"Cho'Gath", "Chogath"};
            case 42 -> new String[] {"Corki"};
            case 122 -> new String[] {"Darius"};
            case 131 -> new String[] {"Diana"};
            case 36 -> new String[] {"Dr. Mundo", "DrMundo"};
            case 119 -> new String[] {"Draven"};
            case 245 -> new String[] {"Ekko"};
            case 60 -> new String[] {"Elise"};
            case 28 -> new String[] {"Evelynn"};
            case 81 -> new String[] {"Ezreal"};
            case 9 -> new String[] {"Fiddlesticks"};
            case 114 -> new String[] {"Fiora"};
            case 105 -> new String[] {"Fizz"};
            case 3 -> new String[] {"Galio"};
            case 41 -> new String[] {"Gangplank"};
            case 86 -> new String[] {"Garen"};
            case 150 -> new String[] {"Gnar"};
            case 79 -> new String[] {"Gragas"};
            case 104 -> new String[] {"Graves"};
            case 887 -> new String[] {"Gwen"};
            case 120 -> new String[] {"Hecarim"};
            case 74 -> new String[] {"Heimerdinger"};
            case 910 -> new String[] {"Hwei"};
            case 420 -> new String[] {"Illaoi"};
            case 39 -> new String[] {"Irelia"};
            case 427 -> new String[] {"Ivern"};
            case 40 -> new String[] {"Janna"};
            case 59 -> new String[] {"Jarvan IV", "JarvanIV"};
            case 24 -> new String[] {"Jax"};
            case 126 -> new String[] {"Jayce"};
            case 202 -> new String[] {"Jhin"};
            case 222 -> new String[] {"Jinx"};
            case 145 -> new String[] {"Kai'Sa", "Kaisa"};
            case 429 -> new String[] {"Kalista"};
            case 43 -> new String[] {"Karma"};
            case 30 -> new String[] {"Karthus"};
            case 38 -> new String[] {"Kassadin"};
            case 55 -> new String[] {"Katarina"};
            case 10 -> new String[] {"Kayle"};
            case 141 -> new String[] {"Kayn"};
            case 85 -> new String[] {"Kennen"};
            case 121 -> new String[] {"Kha'Zix", "Khazix"};
            case 203 -> new String[] {"Kindred"};
            case 240 -> new String[] {"Kled"};
            case 96 -> new String[] {"Kog'Maw", "KogMaw"};
            case 897 -> new String[] {"K'Sante", "KSante"};
            case 7 -> new String[] {"LeBlanc", "Leblanc"};
            case 64 -> new String[] {"Lee Sin", "LeeSin"};
            case 89 -> new String[] {"Leona"};
            case 876 -> new String[] {"Lillia"};
            case 127 -> new String[] {"Lissandra"};
            case 236 -> new String[] {"Lucian"};
            case 117 -> new String[] {"Lulu"};
            case 99 -> new String[] {"Lux"};
            case 54 -> new String[] {"Malphite"};
            case 90 -> new String[] {"Malzahar"};
            case 57 -> new String[] {"Maokai"};
            case 11 -> new String[] {"Master Yi", "MasterYi"};
            case 902 -> new String[] {"Milio"};
            case 21 -> new String[] {"Miss Fortune", "MissFortune"};
            case 62 -> new String[] {"Wukong", "MonkeyKing"};
            case 82 -> new String[] {"Mordekaiser"};
            case 25 -> new String[] {"Morgana"};
            case 950 -> new String[] {"Naafiri"};
            case 267 -> new String[] {"Nami"};
            case 75 -> new String[] {"Nasus"};
            case 111 -> new String[] {"Nautilus"};
            case 518 -> new String[] {"Neeko"};
            case 76 -> new String[] {"Nidalee"};
            case 895 -> new String[] {"Nilah"};
            case 56 -> new String[] {"Nocturne"};
            case 20 -> new String[] {"Nunu & Willump", "Nunu"};
            case 2 -> new String[] {"Olaf"};
            case 61 -> new String[] {"Orianna"};
            case 516 -> new String[] {"Ornn"};
            case 80 -> new String[] {"Pantheon"};
            case 78 -> new String[] {"Poppy"};
            case 555 -> new String[] {"Pyke"};
            case 246 -> new String[] {"Qiyana"};
            case 133 -> new String[] {"Quinn"};
            case 497 -> new String[] {"Rakan"};
            case 33 -> new String[] {"Rammus"};
            case 421 -> new String[] {"Rek'Sai", "RekSai"};
            case 526 -> new String[] {"Rell"};
            case 888 -> new String[] {"Renata Glasc", "Renata"};
            case 58 -> new String[] {"Renekton"};
            case 107 -> new String[] {"Rengar"};
            case 92 -> new String[] {"Riven"};
            case 68 -> new String[] {"Rumble"};
            case 13 -> new String[] {"Ryze"};
            case 360 -> new String[] {"Samira"};
            case 113 -> new String[] {"Sejuani"};
            case 235 -> new String[] {"Senna"};
            case 147 -> new String[] {"Seraphine"};
            case 875 -> new String[] {"Sett"};
            case 35 -> new String[] {"Shaco"};
            case 98 -> new String[] {"Shen"};
            case 102 -> new String[] {"Shyvana"};
            case 27 -> new String[] {"Singed"};
            case 14 -> new String[] {"Sion"};
            case 15 -> new String[] {"Sivir"};
            case 72 -> new String[] {"Skarner"};
            case 901 -> new String[] {"Smolder"};
            case 37 -> new String[] {"Sona"};
            case 16 -> new String[] {"Soraka"};
            case 50 -> new String[] {"Swain"};
            case 517 -> new String[] {"Sylas"};
            case 134 -> new String[] {"Syndra"};
            case 223 -> new String[] {"Tahm Kench", "TahmKench"};
            case 163 -> new String[] {"Taliyah"};
            case 91 -> new String[] {"Talon"};
            case 44 -> new String[] {"Taric"};
            case 17 -> new String[] {"Teemo"};
            case 412 -> new String[] {"Thresh"};
            case 18 -> new String[] {"Tristana"};
            case 48 -> new String[] {"Trundle"};
            case 23 -> new String[] {"Tryndamere"};
            case 4 -> new String[] {"Twisted Fate", "TwistedFate"};
            case 29 -> new String[] {"Twitch"};
            case 77 -> new String[] {"Udyr"};
            case 6 -> new String[] {"Urgot"};
            case 110 -> new String[] {"Varus"};
            case 67 -> new String[] {"Vayne"};
            case 45 -> new String[] {"Veigar"};
            case 161 -> new String[] {"Vel'Koz", "Velkoz"};
            case 711 -> new String[] {"Vex"};
            case 254 -> new String[] {"Vi"};
            case 234 -> new String[] {"Viego"};
            case 112 -> new String[] {"Viktor"};
            case 8 -> new String[] {"Vladimir"};
            case 106 -> new String[] {"Volibear"};
            case 19 -> new String[] {"Warwick"};
            case 498 -> new String[] {"Xayah"};
            case 101 -> new String[] {"Xerath"};
            case 5 -> new String[] {"Xin Zhao", "XinZhao"};
            case 157 -> new String[] {"Yasuo"};
            case 777 -> new String[] {"Yone"};
            case 83 -> new String[] {"Yorick"};
            case 350 -> new String[] {"Yuumi"};
            case 154 -> new String[] {"Zac"};
            case 238 -> new String[] {"Zed"};
            case 221 -> new String[] {"Zeri"};
            case 115 -> new String[] {"Ziggs"};
            case 26 -> new String[] {"Zilean"};
            case 142 -> new String[] {"Zoe"};
            case 143 -> new String[] {"Zyra"};
            default -> new String[] {"Champion not found"};
        };
    }
}
